set-option -add global ui_options terminal_assistant=cat

colorscheme one-dark
hook global RegisterModified '"' %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}
map global normal P '!xsel --output --clipboard<ret>'
map global normal p '<a-!>xsel --output --clipboard<ret>'
map global normal R '|xsel --output --clipboard<ret>'

eval %sh{kak-lsp --kakoune -s $kak_session -c ~/.config/kak-lsp/kak-lsp.toml}
lsp-enable
set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

add-highlighter global/ show-matching
# Make sure my colorschemes 'Whitespace' face ends in '+f'
# See ':doc faces' for more info.
add-highlighter global/ show-whitespaces
add-highlighter global/ number-lines -relative
add-highlighter global/ column 80 default,rgb:404040

set global tabstop 4
set global indentwidth 4

hook global BufOpenFile .* editorconfig-load
hook global BufNewFile .* editorconfig-load

# USERMODE BINDINGS
# -----------------

map global user e ':lsp-find-error --include-warnings<ret>' -docstring 'find lsp error'
map global user h ':lsp-hover<ret>' -docstring 'lsp hover'
map global user f 'x|par w79<ret>' -docstring 'fold lines to 79 characters'
map global user q 'x|sed -E "s/^(> )?/> /"<ret>|par w79<ret>'
map global user u 'xypHr-'
map global user a '|unidecode<ret>'
map global user c ':comment-line<ret>'
map global user k '<a-a>w:man<ret>'
map global user d ':db<ret>'
# map global user
define-command -params 1 insert-image %{echo %sh{scrot -s -o $1}; execute-keys "o!IMAGE %arg{1}<esc>"}
map global user i ':insert-image '
# map global user i %{:prompt image_name %(execute-keys 'ihi<esc>')<ret>}


# EXPERIMENTS
# -----------

declare-option range-specs hidden_lines
define-command hide-line %{
    execute-keys x
    set-option window hidden_lines %val{timestamp} "%val{selection_desc}|"
    try %{ add-highlighter window/ replace-ranges hidden_lines }
}
