#!/bin/python3

import sys
import subprocess

shell = False
command = ""

def run_shell(command):
    result = subprocess.run(command, shell=True, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, text=True)
    sys.stderr.write(result.stderr)
    sys.stdout.write(result.stdout)
    if result.returncode != 0:
        exit(1)

def run(payload, mode):
    result = subprocess.run(mode, input=payload, shell=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    sys.stderr.write(result.stderr)
    sys.stdout.write(result.stdout)
    if result.returncode != 0:
        exit(1)
mode = "verbatim"
payload = ""

for line in sys.stdin:
    if mode == "verbatim":
        parts = line.strip().split(" ", 1)
        if parts[0] == "!BEGIN":
            mode = parts[1]
        else:
            sys.stdout.write(line)
    else:
        if line.strip() == "!END":
            run(payload, mode)
            mode = "verbatim"
            payload = ""
        else:
            payload += line
