[language.java]
filetypes = ["java"]
roots = [".git/"]
command = "/home/chris/r/dotfiles/lsp/jdt-ls.sh"
# https://github.com/eclipse-jdtls/eclipse.jdt.ls

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls", ".git"]
command = "ccls"
args = ["--init={\"request\":{\"timeout\":20000}}"]

[language.python]
filetypes = ["python"]
roots = [".git"]
command = "pylsp"
offset_encoding = "utf-8"

# [language.ocaml]
# extensions = ["ml"]
# filetypes = ["ocaml"]
# roots = [".git/"]
# command = "ocamllsp"
